wandb_version: 1

batch_size:
  value: 512
buffer_size:
  value: 1000000
dynamics_net_arch:
  value:
  - 200
  - 200
  - 200
  - 200
gamma:
  value: 1
learning_rate:
  value: 0.0003
learning_starts:
  value: 100
net_arch:
  value:
  - 512
  - 512
