wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727786676
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.0
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
alpha:
  desc: null
  value: 0.6
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1064456
delay_policy_update:
  desc: null
  value: 3
dynamics_buffer_size:
  desc: null
  value: 163683
dynamics_min_uncertainty:
  desc: null
  value: 1.1300283091842105
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  desc: null
  value: 0.14158714413749982
dynamics_rollout_batch_size:
  desc: null
  value: 38969
dynamics_rollout_freq:
  desc: null
  value: 194
dynamics_rollout_len:
  desc: null
  value: 6
dynamics_rollout_starts:
  desc: null
  value: 4406
dynamics_train_freq:
  desc: null
  value: 438
gamma:
  desc: null
  value: 0.970811108155658
gradient_updates:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.008596953736277786
learning_starts:
  desc: null
  value: 831
min_priority:
  desc: null
  value: 0.1
net_arch:
  desc: null
  value:
  - 256
  - 256
noise_clip:
  desc: null
  value: 0.5
num_q_nets:
  desc: null
  value: 2
policy_noise:
  desc: null
  value: 0.2
tau:
  desc: null
  value: 0.955730510740088
