wandb_version: 1

alpha:
  value: 0.6
batch_size:
  value: 256
buffer_size:
  value: 1675581
delay_policy_update:
  value: 2
dynamics_buffer_size:
  value: 382898
dynamics_min_uncertainty:
  value: 1.2286152879728411
dynamics_net_arch:
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  value: 0.8770684186530211
dynamics_rollout_batch_size:
  value: 34380
dynamics_rollout_freq:
  value: 263
dynamics_rollout_len:
  value: 1
dynamics_rollout_starts:
  value: 1453
dynamics_train_freq:
  value: 222
gamma:
  value: 0.9820984492348398
gradient_updates:
  value: 6
learning_rate:
  value: 0.0023736615173707513
learning_starts:
  value: 968
min_priority:
  value: 0.1
net_arch:
  value:
  - 256
  - 256
noise_clip:
  value: 0.5
num_q_nets:
  value: 2
policy_noise:
  value: 0.2
tau:
  value: 0.2087133146835196
