wandb_version: 1

alpha:
  value: 0.6
batch_size:
  value: 256
buffer_size:
  value: 1913445
delay_policy_update:
  value: 4
dynamics_buffer_size:
  value: 178009
dynamics_min_uncertainty:
  value: 1.0548300427986783
dynamics_net_arch:
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  value: 0.535888799738894
dynamics_rollout_batch_size:
  value: 35259
dynamics_rollout_freq:
  value: 134
dynamics_rollout_len:
  value: 7
dynamics_rollout_starts:
  value: 4057
dynamics_train_freq:
  value: 290
gamma:
  value: 0.9121122483788164
gradient_updates:
  value: 8
learning_rate:
  value: 0.0022986384196363656
learning_starts:
  value: 976
min_priority:
  value: 0.1
net_arch:
  value:
  - 256
  - 256
noise_clip:
  value: 0.5
num_q_nets:
  value: 2
policy_noise:
  value: 0.2
tau:
  value: 0.6735272157753901
