wandb_version: 1

alpha:
  value: 0.6
batch_size:
  value: 256
buffer_size:
  value: 805785
delay_policy_update:
  value: 5
dynamics_buffer_size:
  value: 246935
dynamics_min_uncertainty:
  value: 1.972021149327789
dynamics_net_arch:
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  value: 0.46124894329567534
dynamics_rollout_batch_size:
  value: 40200
dynamics_rollout_freq:
  value: 212
dynamics_rollout_len:
  value: 1
dynamics_rollout_starts:
  value: 1279
dynamics_train_freq:
  value: 539
gamma:
  value: 0.9495331718603106
gradient_updates:
  value: 8
learning_rate:
  value: 0.005312615448961636
learning_starts:
  value: 592
min_priority:
  value: 0.1
net_arch:
  value:
  - 256
  - 256
noise_clip:
  value: 0.5
num_q_nets:
  value: 2
policy_noise:
  value: 0.2
tau:
  value: 0.8118249430006195
