wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727786684
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.0
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
alpha:
  desc: null
  value: 0.6
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1675581
delay_policy_update:
  desc: null
  value: 2
dynamics_buffer_size:
  desc: null
  value: 382898
dynamics_min_uncertainty:
  desc: null
  value: 1.2286152879728411
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  desc: null
  value: 0.8770684186530211
dynamics_rollout_batch_size:
  desc: null
  value: 34380
dynamics_rollout_freq:
  desc: null
  value: 263
dynamics_rollout_len:
  desc: null
  value: 1
dynamics_rollout_starts:
  desc: null
  value: 1453
dynamics_train_freq:
  desc: null
  value: 222
gamma:
  desc: null
  value: 0.9820984492348398
gradient_updates:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0023736615173707513
learning_starts:
  desc: null
  value: 968
min_priority:
  desc: null
  value: 0.1
net_arch:
  desc: null
  value:
  - 256
  - 256
noise_clip:
  desc: null
  value: 0.5
num_q_nets:
  desc: null
  value: 2
policy_noise:
  desc: null
  value: 0.2
tau:
  desc: null
  value: 0.2087133146835196
