wandb_version: 1

algorithm:
  desc: null
  value: EMODPS-EpsNSGAII
num_of_obj:
  desc: null
  value: 4
epsilons:
  desc: null
  value:
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726668203
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.0
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
