wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727950532
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.0
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 512
buffer_size:
  desc: null
  value: 1000000
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
gamma:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0004
learning_starts:
  desc: null
  value: 100
net_arch:
  desc: null
  value:
  - 512
  - 512
