wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727959546
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 13
      - 16
      - 19
      - 23
      - 24
      - 37
      4: 3.11.0
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: global_step
    - 1: metrics/mean_priority
      5: 1
      6:
      - 1
    - 1: metrics/max_priority
      5: 1
      6:
      - 1
    - 1: metrics/min_priority
      5: 1
      6:
      - 1
    - 1: losses/critic_loss
      5: 1
      6:
      - 1
    - 1: losses/policy_loss
      5: 1
      6:
      - 1
batch_size:
  desc: null
  value: 512
buffer_size:
  desc: null
  value: 1000000
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
gamma:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 100
net_arch:
  desc: null
  value:
  - 512
  - 512
total_timesteps:
  desc: null
  value: 10000
ref_point:
  desc: null
  value:
  - 1.0e-07
  - -240.0
  - -240.0
  - 1.0e-07
known_front:
  desc: null
  value: null
num_eval_weights_for_front:
  desc: null
  value: 100
num_eval_episodes_for_front:
  desc: null
  value: 5
num_eval_weights_for_eval:
  desc: null
  value: 50
weight_selection_algo:
  desc: null
  value: gpi-ls
timesteps_per_iter:
  desc: null
  value: 10000
eval_freq:
  desc: null
  value: 1000
eval_mo_freq:
  desc: null
  value: 10000
