wandb_version: 1

env_id:
  desc: null
  value: nile-v0
learning_rate:
  desc: null
  value: 0.0003
num_q_nets:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 128
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 1.0
net_arch:
  desc: null
  value:
  - 256
  - 256
gradient_updates:
  desc: null
  value: 1
alpha:
  desc: null
  value: 0.2
buffer_size:
  desc: null
  value: 1000000
learning_starts:
  desc: null
  value: 1000
seed:
  desc: null
  value: 2
algo:
  desc: null
  value: CAPQL
_wandb:
  desc: null
  value:
    code_path: code/launch_experiment.py
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727964361
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 13
      - 16
      - 19
      - 23
      4: 3.11.0
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
total_timesteps:
  desc: null
  value: 200000
ref_point:
  desc: null
  value:
  - 0.0
  - -240.0
  - -240.0
  - 0.0
known_front:
  desc: null
  value: null
num_eval_weights_for_front:
  desc: null
  value: 100
num_eval_episodes_for_front:
  desc: null
  value: 5
num_eval_weights_for_eval:
  desc: null
  value: 50
eval_freq:
  desc: null
  value: 10000
reset_num_timesteps:
  desc: null
  value: false
