wandb_version: 1

env_id:
  desc: null
  value: nile-v0
learning_rate:
  desc: null
  value: 0.002
num_q_nets:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 128
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 1.0
policy_noise:
  desc: null
  value: 0.2
net_arch:
  desc: null
  value:
  - 512
  - 512
gradient_updates:
  desc: null
  value: 20
delay_policy_update:
  desc: null
  value: 2
min_priority:
  desc: null
  value: 0.1
per:
  desc: null
  value: true
buffer_size:
  desc: null
  value: 1000000
alpha:
  desc: null
  value: 0.6
learning_starts:
  desc: null
  value: 10
dyna:
  desc: null
  value: false
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_rollout_len:
  desc: null
  value: 5
dynamics_min_uncertainty:
  desc: null
  value: 2.0
dynamics_real_ratio:
  desc: null
  value: 0.1
dynamics_train_freq:
  desc: null
  value: 250
dynamics_rollout_starts:
  desc: null
  value: 1000
dynamics_rollout_freq:
  desc: null
  value: 250
dynamics_rollout_batch_size:
  desc: null
  value: 50000
seed:
  desc: null
  value: 2
algo:
  desc: null
  value: GPI-LS Continuous Action
_wandb:
  desc: null
  value:
    code_path: code/launch_experiment.py
    python_version: 3.11.0
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727962852
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.0
      5: 0.17.8
      8:
      - 5
      13: darwin-arm64
